# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Template # <-- THIS MUST BE 'Template'
metadata:
  name: azure-resource-group-creator # This name will appear on the Create page
  title: Azure Resource Group Creator # This title will be shown in Backstage UI
  description: Create a new Azure Resource Group via GitHub Actions and Terraform
  tags:
    - azure
    - terraform
    - resource-group
    - infra
  annotations:
    # This annotation links this template to its TechDocs documentation (if any)
    backstage.io/techdocs-ref: url:https://github.com/marshaldaulkhai/my-azure-infrastructure/tree/main

spec:
  type: service # This template creates a 'service' type component
  owner: user:guest # or your Backstage user like user:marshal
  system: infrastructure-automation
  # This section tells Backstage where the actual template.yaml file is
  template:
    repo: https://github.com/marshaldaulkhai/my-azure-infrastructure
    path: template.yaml
    supports:
      - github
