# .github/workflows/deploy-rg.yml
name: Deploy Azure Resource Group

on:
  # Allows you to run this workflow manually from the GitHub Actions tab
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Name for the Azure Resource Group'
        required: true
        default: 'my-backstage-rg'
      location:
        description: 'Azure Region (e.g., eastus, westeurope)'
        required: true
        default: 'eastus'

jobs:
  deploy_rg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0 # Or your preferred compatible version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # This secret will be configured later

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="resource_group_name=${{ github.event.inputs.resource_group_name }}" \
            -var="location=${{ github.event.inputs.location }}"
